# Nome do Worflow
name: Pipeline CI/CD
# Definir quando o Pipeline será disparado
on: 
  push:
    branches: 
    - main
    workflow_dispatch: # habilitar o botão "RUN WORKFLOW"
    
jobs:
# Primeiro Job: Build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout do código
        uses: actions/checkout@v6
        
      - name: instalação do node
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: instalação das dependencias
        working-directory: ./blog-opiniao
        run: npm install

      - name: Rodar o build
        working-directory: ./blog-opiniao
        run: npm run build
        env:
          CRUDCRUD_URL: ${{ vars.CRUDCRUD_URL}}
