# Nome do Worflow
name: Pipeline CI/CD
# Definir quando o Pipeline será disparado
on: 
  push:
    branches: 
    - main

    paths: # Só dispara se essas pastas forem alteradas
    - "blog-opiniao/src/**"
    - "blog-opiniao/package.json"
    - "blog-opiniao/package-lock.json"
    - ".github/workflows/**"
    
  workflow_dispatch: # habilitar o botão "RUN WORKFLOW"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout do código
        uses: actions/checkout@v6

      - name: instalação do node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: npm
          cache-dependency-path: blog-opiniao/package-lock.json

      - name: instalação das dependencias
        working-directory: ./blog-opiniao
        run: npm ci

      - name: Rodar o build
        working-directory: ./blog-opiniao
        run: npm run build
        env:
          CRUDCRUD_URL: ${{ vars.CRUDCRUD_URL }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout do código
        uses: actions/checkout@v6

      - name: instalação do node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: npm
          cache-dependency-path: blog-opiniao/package-lock.json

      - name: instalação das dependencias
        working-directory: ./blog-opiniao
        run: npm ci

      - name: rodar lint
        working-directory: ./blog-opiniao
        run: npm run lint

      - name: verificar formatação
        working-directory: ./blog-opiniao
        run: npm run format:check

      - name: rodar test
        working-directory: ./blog-opiniao
        run: npm run test
